version: '3'

services:
  backend:
    networks: 
      - backend
    container_name: backend
    image: python:3.8-slim
    volumes:
      - /my/host/directory:/opt/app
    working_dir: /opt/app
    command: bash

  frontend:
    networks: 
      - frontend
    container_name: frontend
    image: node:19-slim
    volumes:
      - /my/host/directory:/opt/app
    working_dir: /opt/app
    command: bash

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge

volumes:
  db-data: