
POST http://localhost:5000/user/create/tomas/heslo HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

###

GET  http://localhost:5000/login/tomas/heslo HTTP/1.1

###

POST http://localhost:5000/login HTTP/1.1
content-type: application/json

{
    "name": "tomas",
    "password": "heslo"
}

###

GET http://localhost:5000/users HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTY4MjA4NTc1NywianRpIjoiYzhlN2M5MTQtYjJiNC00NWYyLWFhYWYtNmEyMzQzMTE1YzU3IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InRvbWFzIiwibmJmIjoxNjgyMDg1NzU3LCJleHAiOjE2ODIwODY2NTd9.Qt0O-ftDUtY6IHUkXiNQf6Xaa7Os_GQB4CujGoHcrIA

